# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Anthillhacks
email: anthillhacks@servelots.com
description: >
  Anthillhacks is held since 2015. 
  It was for 9 days during the Summer of 2015. 
  Then every year for 2-3 days. 
  In 2019 its planned for 2 weeks! 
  The idea of Anthillhacks is to encourage people to meet at 
  a smaller hills nearby and include it in the program 
  (the place matters). And the idea of Anthillhacks is to 
  be inclusive of City folks, of village folks, 
  of women and non-binary, of educated and the low-literate 
  to get to participate and be together.
keywords: >
  technology, nature, ecology, hardware, software, india, data,
  security, futurism, architecture, freedom, art, anthill, ant, iruway
baseurl: ""
url: "https://anthillhacks.in"
twitter_username: "anthillhacks"
github_username: "janastu"
schedule: 

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
collections:
  sessions:
    output: false
  dates:
    output: false
